### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by smlombardi** [r3a1ay/flat-chameleon-sublime-theme#1]
Installed from Package control.  Changed theme in preferences file.  Restarted ST3.

Error:

![screen shot 2015-04-24 at 11 33 18 am](https://cloud.githubusercontent.com/assets/835148/7322424/f0611d2c-ea75-11e4-8675-32e6a7728834.png)

**Comment by r3a1ay** [comment]
Fixed in v1.2.2.
Please wait until `package control` updates the theme.
Meanwhile disable the theme in your user preferences:
```json
"ignored_packages":
[
	"Vintage",
	"Flat Chameleon"
],
```

**Comment by smlombardi** [comment]
I just tried installing from Zip file.  No more error, but no "chameleon" effect either:

![screen shot 2015-04-24 at 12 02 14 pm](https://cloud.githubusercontent.com/assets/835148/7323050/f9896cfc-ea79-11e4-8678-8a49f0ffa3c1.png)

**Comment by r3a1ay** [comment]
Try run `chameleonize` command in command palette.
If it doesn't help please show me your sublime's console messages (`View - Show console`).

**Comment by smlombardi** [comment]
````
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/stevelombardi/Library/Application Support/Sublime Text 3/Packages
state path: /Users/stevelombardi/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/stevelombardi/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "Color Highlighter", "ScopeHunter"]
pre session restore time: 0.287513
using gpu buffer for window
first paint time: 0.380176
startup time: 0.415619
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin AngularJS.AngularJS-sublime-package
reloading plugin AngularJS.jscompletions
reloading plugin AngularJS.message
reloading plugin AngularJS.sublime_commands
reloading plugin AngularJS.viewlocation
reloading plugin AutoCompleteJS.AutoCompleteJS
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin ColorPicker.sublimecp
reloading plugin CSS Color Converter.colorconvert
reloading plugin Emmet.emmet-plugin
reloading plugin JSCS-Formatter.JSCS-Formatter
reloading plugin JSONLint.JSONLint
reloading plugin LESS.less_completions
reloading plugin Origami.origami
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin PowerCursors.power_cursors
reloading plugin SassBeautify.SassBeautify
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin sublime-github.commandline
reloading plugin sublime-github.github
reloading plugin sublime-github.sublime_github
reloading plugin sublime-github.sublime_requests
reloading plugin SublimeLinter-contrib-scss-lint.linter
SublimeLinter: scss linter loaded 
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-jscs.linter
SublimeLinter: jscs linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin Tag.Edit
reloading plugin Tag.Tag
reloading plugin Tag.tag_classes
reloading plugin Tag.tag_close_tag
reloading plugin Tag.tag_close_tag_on_slash
reloading plugin Tag.tag_indent
reloading plugin Tag.tag_insert_as_tag
reloading plugin Tag.tag_lint
reloading plugin Tag.tag_remove
reloading plugin Tag.tag_remove_attributes
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin CSScomb.CSScomb
reloading plugin Flat Chameleon.flat_chameleon
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SFTP.SFTP
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin User.PreSave
plugins loaded
SublimeLinter: debug mode: off 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-04-24 12:49:54, next run at 2015-04-24 13:49:54 or after
FCT: Color map is empty
````

**Comment by r3a1ay** [comment]
Please try to replace this code in file `flat_chameleon.py`:
```python
        try:
            plist = readPlistFromBytes(
                sublime.load_binary_resource(self.color_scheme))
        except:
            return
```
With this:
```python
        plist = readPlistFromBytes(
            sublime.load_binary_resource(self.color_scheme))
```
Restart `Sublime Text`, run `chameleonize` command and show me messages from console.

**Comment by r3a1ay** [comment]
Or install 1.2.4 version via Package Control.

**Comment by smlombardi** [comment]
````
no command for selector: noop:
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "flat_chameleon in /Users/stevel/Library/Application Support/Sublime Text 3/Installed Packages/Flat Chameleon.sublime-package", line 102, in run
  File "flat_chameleon in /Users/stevel/Library/Application Support/Sublime Text 3/Installed Packages/Flat Chameleon.sublime-package", line 156, in get_color_map
AttributeError: 'FCColorSchemeListener' object has no attribute 'color_map'
````

**Comment by r3a1ay** [comment]
Thanks, fixed that in 1.2.5.
Try when it will be available in package control.
Or download zip archive.

**Comment by smlombardi** [comment]
OK,this is ridiculous.  Are you even testing this?

````
Traceback (most recent call last):
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Flat Chameleon/flat_chameleon.py", line 178, in parse_scheme
    plist = readPlistFromBytes(res)
  File "./plistlib.py", line 104, in readPlistFromBytes
  File "./plistlib.py", line 76, in readPlist
  File "./plistlib.py", line 378, in parse
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 810, column 33

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Flat Chameleon/flat_chameleon.py", line 154, in init
    self.parse_scheme()
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Flat Chameleon/flat_chameleon.py", line 180, in parse_scheme
    self.add_error(msg_er_scheme, self.color_scheme)
AttributeError: 'FCColorSchemeListener' object has no attribute 'add_error'
Emmet: Loading Emmet extensions from /Users/stevel/emmet
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-04-24 16:56:06, next run at 2015-04-24 17:56:06 or after
Traceback (most recent call last):
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Flat Chameleon/flat_chameleon.py", line 178, in parse_scheme
    plist = readPlistFromBytes(res)
  File "./plistlib.py", line 104, in readPlistFromBytes
  File "./plistlib.py", line 76, in readPlist
  File "./plistlib.py", line 378, in parse
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 810, column 33

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Flat Chameleon/flat_chameleon.py", line 102, in run
    self.color_map = FCColorSchemeListener.inst.get_color_map(self.view)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Flat Chameleon/flat_chameleon.py", line 158, in get_color_map
    self.parse_scheme()
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Flat Chameleon/flat_chameleon.py", line 180, in parse_scheme
    self.add_error(msg_er_scheme, self.color_scheme)
AttributeError: 'FCColorSchemeListener' object has no attribute 'add_error'
````

**Comment by r3a1ay** [comment]
Can you share your color scheme file?

**Comment by smlombardi** [comment]
https://packagecontrol.io/packages/Inspired%20GitHub%20Color%20Scheme

**Comment by r3a1ay** [comment]
No issues with this color scheme for me.
You have disabled `ScopeHunter` package. Does it works for you?
It has similar [issue](https://github.com/facelessuser/ScopeHunter/issues/5). Try to [revert](http://www.sublimetext.com/docs/3/revert.html) Sublime Text.
